sudo: true
language: python
python:
- '2.7'
install:
- ./test/install.sh
script: 
- ./test/run_tests.sh
deploy:
  provider: pypi
  user: welldone
  password:
    secure: R+2My9xlrw2RSzIe9bCCdecsfCnebp0ahMFpQHxKkadPCLTm8441PubrMUeTOqFrlO/uoZidl7uC9WWG3aen8ivortmNSE3yPMo4hP5r6kdQwffAQvqrZERrroOvl/q2edSxokmfxXxkdwqknyvvR49a9Q00c99waQhSHQwhlQs=
  on:
    repo: WellDone/pymomo
    tags: true
    all_branches: true
